// This is automatically generated code -- do not edit!
// Generated from xml/form_templates.xml 
#include <vector>
namespace xmlResources
{


  const char * form_templates_xml1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
  "<messages xmlns:if=\"Wt.WTemplate.conditions\">\r\n"
  "  <message id=\"template.registration\">\r\n"
  "    <div class=\"Wt-form Wt-auth-registration\">\r\n"
  "      <h2>${tr:Wt.Auth.registration-form-title}</h2>\r\n"
  "      <p>${tr:Wt.Auth.registration-form-info}</p>\r\n"
  "\r\n"
  "      ${password-description}\r\n"
  "\r\n"
  "      <div class=\"Wt-fields\">\r\n"
  "        ${<if:user-name>}\r\n"
  "          <label for=\"${id:user-name}\">${user-name-label}\r\n"
  "            ${user-name-info class=\"Wt-info\"}\r\n"
  "            ${confirm-is-you class=\"Wt-info\"}\r\n"
  "          </label>\r\n"
  "          ${user-name}\r\n"
  "        ${</if:user-name>}\r\n"
  "\r\n"
  "        ${<if:choose-password>}\r\n"
  "          <label for=\"${id:choose-password}\">${tr:Wt.Auth.choose-password}\r\n"
  "            ${choose-password-info class=\"Wt-info\"}\r\n"
  "          </label>\r\n"
  "          ${choose-password}\r\n"
  "\r\n"
  "          <label for=\"${id:repeat-password}\">${tr:Wt.Auth.repeat-password}\r\n"
  "            ${repeat-password-info class=\"Wt-info\"}\r\n"
  "          </label>\r\n"
  "          ${repeat-password}\r\n"
  "        ${</if:choose-password>}\r\n"
  "\r\n"
  "        ${<if:email>}\r\n"
  "          <label for=\"${id:email}\">${tr:Wt.Auth.email}\r\n"
  "            ${email-info class=\"Wt-info\"}\r\n"
  "          </label>\r\n"
  "          ${email}\r\n"
  "        ${</if:email>}\r\n"
  "      </div>\r\n"
  "\r\n"
  "      ${<if:oauth>}\r\n"
  "        <br clear=\"both\" />\r\n"
  "        ${oauth-description}\r\n"
  "        <label>${tr:Wt.Auth.oauth}\r\n"
  "          <span class=\"Wt-info\">${tr:Wt.Auth.oauth-info}</span>\r\n"
  "        </label>\r\n"
  "        ${icons}\r\n"
  "      ${</if:oauth>}\r\n"
  "\r\n"
  "      <div class=\"Wt-buttons\">\r\n"
  "        ${ok-button} ${cancel-button}\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "  <message id=\"OJ.template.login\">\r\n"
  "    <div class=\"left-stretch\"/>\r\n"
  "    <div class=\"password-auth\">\r\n"
  "         <div class=\"username-auth\">\r\n"
  "          ${block:OJ.Auth.field user-name}\r\n"
  "          ${block:OJ.Auth.fieldremember remember-me}\r\n"
  "	  ${block:OJ.Auth.fieldpassword password}\r\n"
  "          <div class=\"lost-password\">${lost-password}</div>\r\n"
  "         </div>\r\n"
  "    </div>\r\n"
  "    <div class=\"right-column\">\r\n"
  "      ${tr:OJ.Auth.donthave}\r\n"
  "      <div class=\"register-here\">${register}${<if:oauth>} ${tr:OJ.Auth.orlogin}:${</if:oauth>}</div>\r\n"
  "      ${<if:oauth>}\r\n"
  "	  ${icons}\r\n"
  "      ${</if:oauth>}\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "  <message id=\"OJ.template.loggedin\">\r\n"
  "  </message>\r\n"
  "  <message id=\"OJ.Auth.field\">\r\n"
  "    <![CDATA[\r\n"
  "    ${<if:{1}>}\r\n"
  "    <div class=\"form-inline\">\r\n"
  "    <div class=\"form-group\">\r\n"
  "    <label for=\"${id:{1}}\" class=\"control-label\">\r\n"
  "      ${tr:OJ.Auth.{1}}\r\n"
  "    </label>\r\n"
  "    ${{1}}\r\n"
  "    </div>\r\n"
  "    </div>\r\n"
  "    ${</if:{1}>}\r\n"
  "    ]]>\r\n"
  "  </message>\r\n"
  "  <message id=\"OJ.Auth.fieldremember\">\r\n"
  "    <![CDATA[\r\n"
  "    ${<if:{1}>}\r\n"
  "    <div class=\"form-inline\">\r\n"
  "    <div class=\"form-group form-rememberme\">\r\n"
  "    ${{1}}\r\n"
  "    <label for=\"${id:{1}}\" class=\"remember-label\">\r\n"
  "      ${tr:OJ.Auth.{1}}\r\n"
  "    </label>\r\n"
  "    </div>\r\n"
  "    </div>\r\n"
  "    ${</if:{1}>}\r\n"
  "    ]]>\r\n"
  "  </message>\r\n"
  "  <message id=\"OJ.Auth.fieldpassword\">\r\n"
  "    <![CDATA[\r\n"
  "    ${<if:{1}>}\r\n"
  "    <div class=\"form-inline\">\r\n"
  "    <div class=\"form-group form-password\">\r\n"
  "    <label for=\"${id:{1}}\" class=\"control-label\">\r\n"
  "      ${tr:OJ.Auth.{1}}\r\n"
  "    </label>\r\n"
  "    ${{1}} ${login}\r\n"
  "    </div>\r\n"
  "    </div>\r\n"
  "    ${</if:{1}>}\r\n"
  "    ]]>\r\n"
  "  </message>\r\n"
  "  <message id=\"lineEdit-template\">\r\n"
  "    <div class=\"form-inline\">\r\n"
  "      <div class=\"form-group\">\r\n"
  "        <label for=\"${id:edit}\">${label}</label>\r\n"
  "        ${edit}\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "  <message id=\"comboBox-template\">\r\n"
  "    <div class=\"form-inline\">\r\n"
  "      <div class=\"form-group\">\r\n"
  "        <label for=\"${id:combo}\">${label}</label>\r\n"
  "        ${combo}\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "  <message id=\"settingsField-template\">\r\n"
  "    <div class=\"form-inline oj-form-inline\">\r\n"
  "      <div class=\"form-group oj-settings-group\">\r\n"
  "        <label for=\"${id:{1}-setting}\">${tr:{1}-label}</label>\r\n"
  "        ${{1}-setting}\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "  <message id=\"mailField-template\">\r\n"
  "    <div class=\"form-inline oj-form-inline\">\r\n"
  "      <div class=\"form-group oj-settings-group\">\r\n"
  "        <label for=\"${id:{1}-setting}\">${tr:{1}-label}</label>\r\n"
  "        ${{1}-setting} <i>{1}</i>\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "  <message id=\"admin-settings-general\">\r\n"
  "    ${block:settingsField-template sitetitle}\r\n"
  "    ${block:settingsField-template sitelogo}\r\n"
  "    ${block:settingsField-template sitecolor}\r\n"
  "    ${block:settingsField-template googleanalytics}\r\n"
  "    <div class=\"oj-settings-buttons\">${apply-button} ${reset-button}</div>\r\n"
  "  </message>\r\n"
  "  <message id=\"admin-settings-mail\">\r\n"
  "    ${block:mailField-template smtp-self-host}\r\n"
  "    ${block:mailField-template smtp-host}\r\n"
  "    ${block:mailField-template smtp-port}\r\n"
  "    ${block:mailField-template smtp-auth-username}\r\n"
  "    ${block:mailField-template smtp-auth-password}\r\n"
  "    ${block:mailField-template smtp-auth-method}\r\n"
  "    ${block:mailField-template smtp-transport-encryption}\r\n"
  "    ${block:mailField-template auth-mail-sender-name}\r\n"
  "    ${block:mailField-template auth-mail-sender-address}\r\n"
  "    ${tr:yourconfigfile} <b>${config-file-path}</b><br/>\r\n"
  "    ${tr:changesmustbedonethere}\r\n"
  "    <div class=\"form-inline oj-form-inline\">\r\n"
  "      <div class=\"form-group oj-settings-group\">\r\n"
  "        <label for=\"${id:test-mail}\">${tr:test-mail-label}</label>\r\n"
  "        ${test-mail} ${test-mail-button}\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "  <message id=\"settings-account\">\r\n"
  "    <div class=\"oj-settings-avatar\">${avatar-image}</div>\r\n"
  "    <div class=\"form-inline oj-form-inline\">\r\n"
  "      <div class=\"form-group oj-settings-group\">\r\n"
  "        <label>${tr:avatar-label}</label>\r\n"
  "        ${avatar-none-setting}\r\n"
  "	${avatar-gravatar-setting}\r\n"
  "        ${avatar-custom-setting}\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "    ${upload-avatar}\r\n"
  "    ${block:settingsField-template username}\r\n"
  "    ${block:settingsField-template email}\r\n"
  "    ${block:settingsField-template telegramUsername}\r\n"
  "    ${block:settingsField-template firstname}\r\n"
  "    ${block:settingsField-template lastname}\r\n"
  "    ${block:settingsField-template birthday}\r\n"
  "    <div class=\"form-inline oj-form-inline\">\r\n"
  "      <div class=\"form-group oj-settings-group\">\r\n"
  "        <label for=\"${id:country-setting}\">${tr:country-label}</label>\r\n"
  "        ${country-setting} ${country-flag}\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "    ${block:settingsField-template institution}\r\n"
  "    ${block:settingsField-template uvaid}\r\n"
  "    <div class=\"oj-settings-buttons\">${apply-button} ${reset-button}</div>\r\n"
  "  </message>\r\n"
  "  <message id=\"settings-security\">\r\n"
  "    ${block:settingsField-template changepassword}\r\n"
  "    ${block:settingsField-template twofa}\r\n"
  "  </message>\r\n"
  "  <message id=\"settings-notifications\">\r\n"
  "    ${notifications-table}\r\n"
  "    <div class=\"oj-settings-buttons\">${apply-button} ${reset-button}</div>\r\n"
  "  </message>\r\n"
  "  <message id=\"addCategory-template\">\r\n"
  "    <div class=\"form-group\">\r\n"
  "      <label for=\"${id:tree}\">${treelabel}</label><br/>\r\n"
  "      ${rootcheckbox}\r\n"
  "      ${tree}\r\n"
  "    </div>\r\n"
  "    <div class=\"form-group\">\r\n"
  "      <label for=\"${id:title}\">${titlelabel}</label>\r\n"
  "      ${title}\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "  <message id=\"addProblem-template\">\r\n"
  "    <div class=\"form-group\">\r\n"
  "      <label for=\"${id:id}\">${idlabel}</label>\r\n"
  "      ${id}\r\n"
  "    </div>\r\n"
  "    <div class=\"form-group\">\r\n"
  "      <label for=\"${id:title}\">${titlelabel}</label>\r\n"
  "      ${title}\r\n"
  "    </div>\r\n"
  "    <div class=\"form-group\">\r\n"
  "      <label for=\"${id:htmldescription}\">${htmldescriptionlabel}</label>\r\n"
  "      ${htmldescription}\r\n"
  "    </div>\r\n"
  "    <div class=\"form-group\">\r\n"
  "      ${htmlprogress}\r\n"
  "    </div>\r\n"
  "    <div class=\"form-group\">\r\n"
  "      <label for=\"${id:pdfdescription}\">${pdfdescriptionlabel}</label>\r\n"
  "      ${pdfdescription}\r\n"
  "    </div>\r\n"
  "    <div class=\"form-group\">\r\n"
  "      ${pdfprogress}\r\n"
  "    </div>\r\n"
  "    <div class=\"form-group\">\r\n"
  "      <label for=\"${id:categories}\">${categorieslabel}</label>\r\n"
  "      ${categories}\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "</messages>\r\n"
  "";
  std::vector<const char *> form_templates_xml()
  {
    std::vector<const char *> retval;

    retval.push_back(form_templates_xml1);

    return retval;
  }
}